name = "TMLE"
uuid = "8afdd2fb-6e73-43df-8b62-b1650cd9c8cf"
authors = ["Olivier Labayle"]
version = "0.5.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJGLMInterface = "caf8df21-4939-456d-ac9c-5fefbfb04c0c"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CategoricalArrays = "0.10"
HypothesisTests = "0.10"
MLJBase = "0.19"
MLJGLMInterface = "0.1, 0.2"
MLJModels = "0.15"
TableOperations = "1.2"
Tables = "1.5"
julia = "1.6, 1.7"
Missings = "1.0"
